version: "3.3"
services:
  db:
    image: harbor.ocean.bkjk-inc.com/bkjk-bkcloud/mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'stark'
    ports:
      - '3306:3306'
    volumes:
      - "/home/sailor/stark/mysql:/var/lib/mysql"